minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Ritvik Nag"
subtitle                 : # site tagline that appears below site title in masthead
title_separator          : "-"
name                     : &name "Ritvik Nag"
description: &description >- # this means to ignore newlines until "baseurl:"
  Software Dev & Autom. Engineer. CS Grad Student @ [George Mason](https://www.gmu.edu).
  Love to run, read, cook, write, & game!
url                      : &url "https://ritviknag.com"
baseurl                  : ""
domain                   : rnag.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
repository               : "rnag/rnag.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : true
words_per_minute         : 200
# analytics:
#   provider               : "clarity"
#   clarity:
#     project_id           : "er6rxn3sjb"
comments:
  provider               : "disqus"
  disqus:
    shortname            : "ritvik-nag"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : true
search_provider          : lunr
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

twitter:
  username               : &twitter RitvikNag

# github: [metadata]

# Build settings
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "US/Eastern"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

show_excerpts: true # set to true to show excerpts on the homepage


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
# minima:
#   date_format: "%b %-d, %Y"

author:
  name             : *name
  avatar           : "/assets/images/ritvik-nag.jpg"
  bio              : *description
  location         : "Herndon, VA"
  email            : "rv.kvetch@gmail.com"
  # uri              : "https://ritviknag.com"
  twitter          :  *twitter
  linkedin         :  ritviknag
  instagram        :  rv.kvetch
  github           :  rnag
  stackoverflow    :  10237506/rv-kvetch
  steam            :  *twitter

  # TODO Do I need a YouTube?

  reviews:
    amazon         : "AGHUUSBG63RRWQ5EEME5ZFNTYVEA"
    google_maps    : "115125010633237882853"
    yelp           : "bV7D-Sjrd-nTT1-X7P9dzQ"

# TODO: Let's DRY this, and parametrize as above.
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:rv.kvetch@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: *url
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/RitvikNag"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ritviknag"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rv.kvetch"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rnag"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/10237506/rv-kvetch"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

encoding: "UTF-8"
markdown_ext: "md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
